[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang.workspace = true
anchor-spl.workspace = true
solana-program.workspace = true
solana-sdk.workspace = true
litesvm.workspace = true
testt.workspace = true


